# Speed Processing of Lists Vs Numpy Arrays

In [ ]:
from time import process_time
import numpy as np

With Lists

In [ ]:
list = [a for a in range(20000)]
start_time = process_time()
new_list = [a**2 for a in list]
end_time = process_time()
ltime = end_time - start_time
print(ltime, type(list))

0.0015459739999998945 <class 'list'>


With NumPy

In [ ]:
np_array = np.array([a for a in range(20000)])
start_time = process_time()
new_array = np_array**2
end_time = process_time()
ntime = end_time - start_time
print(ntime, type(np_array))

0.0010304769999995855 <class 'numpy.ndarray'>


(20000,)

In [ ]:
if (ltime > ntime):
  print("NumPy is faster")
else:
  print("List is faster")

NumPy is faster


# Dimensonal Arrays

One-dimensional Array

In [ ]:
one_d = np.array([1,2,4,4])
print(one_d)
one_d.shape

[1 2 4 4]


(4,)

Multi-dimensional Array

In [ ]:
mult_d = np.array([(1,2,4,2),(2,43,2,5),(4,7,8,8)])
print(mult_d)
mult_d.shape

[[ 1  2  4  2]
 [ 2 43  2  5]
 [ 4  7  8  8]]


(3, 4)

Representing in floating point data type

In [ ]:
mult_d = np.array([(1,2,4,2),(2,43,2,5),(4,7,8,8)],dtype=float)
print(mult_d)
mult_d.shape

[[ 1.  2.  4.  2.]
 [ 2. 43.  2.  5.]
 [ 4.  7.  8.  8.]]


(3, 4)

Placeholder Array

In [ ]:
# Using zero function create the arrays of the given shape.
plc_hld_arr = np.zeros((5,6)) # In "(5,6)" '5' represents number of rows and '6' represents number of columns.
print(plc_hld_arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Ones Array

In [ ]:
# Creating array of only ones.
ones_arr = np.ones((6,7))
print(ones_arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Particular Value Array

In [ ]:
# Creating array of particular value.
part_val_arr = np.full((4,3), 6) # The second argument is the value of which the whole array is to be made.
print(part_val_arr)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


Identity Matrix

In [ ]:
# Creating identity matrix
iden_mat = np.eye(6) # The argument shows there should be 6 '1' on the diagonal or in other words the matrix should be '6x6'.
print(iden_mat)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Random Values Array

In [ ]:
# Creating random arrays with random values.
rand_arr = np.random.random((4,5))
print(rand_arr) # The values in the arrays is in between 0 and 1.

[[0.92483247 0.46064823 0.67978321 0.66280078 0.25307831]
 [0.92758423 0.74486175 0.0439258  0.66960807 0.51154185]
 [0.53328183 0.55112439 0.73061486 0.76193055 0.41503278]
 [0.85358341 0.25324142 0.52576461 0.47028169 0.61934273]]


Random Values Array With Specific Range

In [ ]:
# Creatinf random array with specific values range.
rand_spec_arr = np.random.randint(10,20,(4,6))
print(rand_spec_arr)

[[14 17 12 15 16 13]
 [17 19 13 11 18 11]
 [18 18 15 13 17 13]
 [13 13 13 19 10 12]]


Evenly Spaced Array --> Required number of values

In [ ]:
# Creating evenly spaced array by specifying required number of values
even_spc_arr = np.linspace(0,20,5) # 1st and 2nd arguments are range and 3rd argument is the required number of values.
print(even_spc_arr)


[ 0.  5. 10. 15. 20.]


Evenly Spaced Array --> Step size

In [ ]:
# Creating evenly spaced array by specifying step size.
stpize_arr = np.arange(0,30,6) # The 3rd argument representing the step size value.
print(stpize_arr)

[ 0  6 12 18 24]


Converting List To An Array

In [ ]:
# Converting a list to an array.
list2 = [3,4,323,42,4]
conv_arr = np.asarray(list2)
print(conv_arr)
type(conv_arr)

[  3   4 323  42   4]


numpy.ndarray

Analysing An Array

In [ ]:
arr = np.random.randint(0,8,(4,5))
print(arr)

[[6 6 5 3 0]
 [4 0 6 3 6]
 [4 7 6 0 3]
 [6 5 3 3 4]]


In [ ]:
# Checking the shape of an array
arr.shape

(4, 5)

In [ ]:
# Checking dimensions of an array
arr.ndim

2

In [ ]:
# Checking number of elements in an array
arr.size

20

In [ ]:
# Checking data type of values of an array
arr.dtype

dtype('int64')