# Speed Processing of Lists Vs Numpy Arrays

In [ ]:
from time import process_time
import numpy as np

With Lists

In [ ]:
list = [a for a in range(20000)]
start_time = process_time()
new_list = [a**2 for a in list]
end_time = process_time()
ltime = end_time - start_time
print(ltime, type(list))

0.002496248000003476 <class 'list'>


With NumPy

In [ ]:
np_array = np.array([a for a in range(20000)])
start_time = process_time()
new_array = np_array**2
end_time = process_time()
ntime = end_time - start_time
print(ntime, type(np_array))

0.0025711190000023976 <class 'numpy.ndarray'>


In [ ]:
if (ltime > ntime):
  print("NumPy is faster")
else:
  print("List is faster")

List is faster


# Dimensonal Arrays

One-dimensional Array

In [ ]:
one_d = np.array([1,2,4,4])
print(one_d)
one_d.shape

[1 2 4 4]


(4,)

Multi-dimensional Array

In [ ]:
mult_d = np.array([(1,2,4,2),(2,43,2,5),(4,7,8,8)])
print(mult_d)
mult_d.shape

[[ 1  2  4  2]
 [ 2 43  2  5]
 [ 4  7  8  8]]


(3, 4)

Representing in floating point data type

In [ ]:
mult_d = np.array([(1,2,4,2),(2,43,2,5),(4,7,8,8)],dtype=float)
print(mult_d)
mult_d.shape

[[ 1.  2.  4.  2.]
 [ 2. 43.  2.  5.]
 [ 4.  7.  8.  8.]]


(3, 4)

Placeholder Array

In [ ]:
# Using zero function create the arrays of the given shape.
plc_hld_arr = np.zeros((5,6)) # In "(5,6)" '5' represents number of rows and '6' represents number of columns.
print(plc_hld_arr)

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


Ones Array

In [ ]:
# Creating array of only ones.
ones_arr = np.ones((6,7))
print(ones_arr)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


Particular Value Array

In [ ]:
# Creating array of particular value.
part_val_arr = np.full((4,3), 6) # The second argument is the value of which the whole array is to be made.
print(part_val_arr)

[[6 6 6]
 [6 6 6]
 [6 6 6]
 [6 6 6]]


Identity Matrix

In [ ]:
# Creating identity matrix
iden_mat = np.eye(6) # The argument shows there should be 6 '1' on the diagonal or in other words the matrix should be '6x6'.
print(iden_mat)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


Random Values Array

In [ ]:
# Creating random arrays with random values.
rand_arr = np.random.random((4,5))
print(rand_arr) # The values in the arrays is in between 0 and 1.

[[0.68231888 0.36654424 0.18615563 0.0395873  0.18520043]
 [0.14876245 0.58412164 0.69511797 0.16981854 0.89125977]
 [0.59027993 0.03910422 0.22568874 0.37225683 0.74182911]
 [0.33656993 0.71621424 0.66226961 0.59632871 0.52218649]]


Random Values Array With Specific Range

In [ ]:
# Creating random array with specific values range.
rand_spec_arr = np.random.randint(10,20,(4,6))
print(rand_spec_arr)

[[18 15 15 11 15 16]
 [10 13 17 16 13 16]
 [16 13 19 13 17 10]
 [11 10 16 16 18 13]]


Evenly Spaced Array --> Required number of values

In [ ]:
# Creating evenly spaced array by specifying required number of values
even_spc_arr = np.linspace(0,20,5) # 1st and 2nd arguments are range and 3rd argument is the required number of values.
print(even_spc_arr)


[ 0.  5. 10. 15. 20.]


Evenly Spaced Array --> Step size

In [ ]:
# Creating evenly spaced array by specifying step size.
stpize_arr = np.arange(0,30,6) # The 3rd argument representing the step size value.
print(stpize_arr)

[ 0  6 12 18 24]


Converting List To An Array

In [ ]:
# Converting a list to an array.
list2 = [3,4,323,42,4]
conv_arr = np.asarray(list2)
print(conv_arr)
type(conv_arr)

[  3   4 323  42   4]


numpy.ndarray

# Analysing An Array

In [ ]:
arr = np.random.randint(0,8,(4,5))
print(arr)

[[2 1 1 0 0]
 [3 1 2 2 0]
 [2 7 3 3 1]
 [5 3 0 2 5]]


In [ ]:
# Checking the shape of an array
arr.shape

(4, 5)

In [ ]:
# Checking dimensions of an array
arr.ndim

2

In [ ]:
# Checking number of elements in an array
arr.size

20

In [ ]:
# Checking data type of values of an array
arr.dtype

dtype('int64')

# Mathematical Operations On An Array

'+' sign with lists

In [ ]:
# Using '+' sign in lists
list1 = [1,2,5,4,3]
list2 = [5,37,3,7,3,6]
print(list1 + list2) # In lists '+' sign concatenate or join two lists.

[1, 2, 5, 4, 3, 5, 37, 3, 7, 3, 6]


1st method - Arithmatic operators on arrays

In [ ]:
# 1st method - Using arithmatic operators in arrays
arr1 = np.random.randint(0,10,(3,3))
arr2 = np.random.randint(10,20,(3,3))
print("Array-1:\n", arr1)
print("Array-2:\n", arr2)

print("Sum:\n", arr1 + arr2)
print("Subtraction:\n", arr1 - arr2)
print("Multiplication:\n", arr1 * arr2)
print("Division:\n", arr1 / arr2) # obtaining quotients
print("Modulus:\n", arr1 % arr2) # obtaining remainders

Array-1:
 [[7 6 5]
 [5 4 6]
 [1 9 0]]
Array-2:
 [[14 14 19]
 [15 13 13]
 [12 10 15]]
Sum:
 [[21 20 24]
 [20 17 19]
 [13 19 15]]
Subtraction:
 [[ -7  -8 -14]
 [-10  -9  -7]
 [-11  -1 -15]]
Multiplication:
 [[98 84 95]
 [75 52 78]
 [12 90  0]]
Division:
 [[0.5        0.42857143 0.26315789]
 [0.33333333 0.30769231 0.46153846]
 [0.08333333 0.9        0.        ]]
Modulus:
 [[7 6 5]
 [5 4 6]
 [1 9 0]]


2nd method - Arithmatic functions on arrays

In [ ]:
# 2nd method - Using arithmatic functions on arrays
arr3 = np.random.randint(30,40,(3,3))
arr4 = np.random.randint(40,50,(3,3))
print("Array-3:\n", arr3)
print("Array-4:\n", arr4)

print("Sum:\n", np.add(arr3,arr4))
print("Subtraction:\n", np.subtract(arr3,arr4))
print("Multiplication:\n", np.multiply(arr3,arr4))
print("Division:\n", np.divide(arr3,arr4)) # obtaining quotients
print("Modulus:\n", np.mod(arr3,arr4)) # obtaining remainders

Array-3:
 [[38 34 39]
 [37 31 30]
 [35 36 35]]
Array-4:
 [[49 45 47]
 [45 45 42]
 [46 40 43]]
Sum:
 [[87 79 86]
 [82 76 72]
 [81 76 78]]
Subtraction:
 [[-11 -11  -8]
 [ -8 -14 -12]
 [-11  -4  -8]]
Multiplication:
 [[1862 1530 1833]
 [1665 1395 1260]
 [1610 1440 1505]]
Division:
 [[0.7755102  0.75555556 0.82978723]
 [0.82222222 0.68888889 0.71428571]
 [0.76086957 0.9        0.81395349]]
Modulus:
 [[38 34 39]
 [37 31 30]
 [35 36 35]]


# Array Manipulation

1st method - Transpose function

In [ ]:
# 1st method - Using transpose function
array1 = np.random.randint(0,10,(2,3))
print("1st Array:\n", array1)
print("Shape of 1st array:\n", array1.shape)

trans1 = np.transpose(array1)
print("Transpose of 1st array:\n", trans1)
print("Shape of 1st transposed array:\n", trans1.shape)

1st Array:
 [[3 8 2]
 [5 1 2]]
Shape of 1st array:
 (2, 3)
Transpose of 1st array:
 [[3 5]
 [8 1]
 [2 2]]
Shape of 1st transposed array:
 (3, 2)


2nd method - 'T' attribute of 'arr'

In [ ]:
# 2nd method - Using 'T' attribute of 'arr'
array2 = np.random.randint(0,10,(2,3))
print("2nd Array:\n", array2)
print("Shape of 2nd array:\n", array2.shape)

trans2 = array2.T
print("Transpose of 2nd array:\n", trans2)
print("Shape of 2nd transposed array:\n", trans2.shape)

2nd Array:
 [[2 3 5]
 [3 8 2]]
Shape of 2nd array:
 (2, 3)
Transpose of 2nd array:
 [[2 3]
 [3 8]
 [5 2]]
Shape of 2nd transposed array:
 (3, 2)


Reshaping an array

In [ ]:
# Reshaping an array
norm_array = np.random.randint(0,10,(2,3))
print("Normal Array:\n", norm_array)
print("Shape of normal array:\n", norm_array.shape)

resh_array = norm_array.reshape(3,2)
print("Reshaped Array:\n", resh_array)
print("Shape of reshaped array:\n", resh_array.shape)

Normal Array:
 [[2 0 5]
 [9 3 1]]
Shape of normal array:
 (2, 3)
Reshaped Array:
 [[2 0]
 [5 9]
 [3 1]]
Shape of reshaped array:
 (3, 2)


# Summary

In [149]:
# 1, Speed Processing of Lists Vs Numpy Arrays
#    NumPy arrays are faster than list

# 2, Dimensonal Arrays

# One dimensional array
one_d = np.array([3,53,34,3,3])
print("1D Array:\n", one_d)

# Multi dimensional array
mult_d = np.array([(2,32,2,3),(3,4,3,2),(3,42,4,2)])
print("Multi-dimensional Array:\n", mult_d)

# Representation in floating numbers
mult_d_f = np.array([(3,3,5,3),(2,5,2,4),(3,53,4,34)],dtype=float)
print("Representation in floating data type:\n", mult_d_f)

# Placeholder - 0 array
plc_hld_arr = np.zeros((2,3))
print("Placeholder - 0 Array:\n", plc_hld_arr)

# Placeholder - 1 array
plc_hld_arr = np.ones((2,3))
print("Placeholder - 1 Array:\n", plc_hld_arr)

# Particular value array
part_val_arr = np.full((3,3), 5)
print("Particular value array:\n", part_val_arr)

# Identity Matrix
iden_mat = np.eye(3,3)
print("Identity matrix:\n", iden_mat)

# Random values array
rand_arr = np.random.random((4,5))
print("Random value array:\n", rand_arr)

# Random value arraynwith specific range
rand_spec_arr = np.random.randint(0,10,(4,5))
print("Random value array with specific range:\n", rand_spec_arr)

# Evenly spaced array with required number of values
even_spc_arr = np.linspace(0,20,6)
print("Evenly spaced array with required number of values:\n", even_spc_arr)

# Evenly spaced array with stepsize
stpize_arr = np.arange(0,20,6)
print("Evenly spaced array with stepsize:\n", stpize_arr)

# Converting list to array
list1 = [1,4,24,4,4]
conv_arr = np.asarray(list1)
print("Coverted list to array:\n", conv_arr)

# 3, Analysing An Array
arr = np.random.randint(0,10,(4,4))

# Shape of array
print("Shape of arr:\n", arr.shape)

# Dimension of array
print("Dimension of arr:\n", arr.ndim)

# Number of elements in array
print("Size of the arr:\n", arr.size)

# Data type of values of array
print("Data type of arr:\n", arr.dtype)

# 4, Mathematical Operations On An Array

# List concatenation
list1 = [2,43,34,23,2]
list2 = [342,442,4,424,4,4]
print("Concatenated lists:\n", list1 + list2)

# Arithmatic operations on arrays using operators
arr1 = np.random.randint(0,10,(3,4))
arr2 = np.random.randint(10,20,(3,4))

print("Sum:\n", arr1 + arr2)
print("Subtraction:\n", arr1 - arr2)
print("Multiplication:\n", arr1 * arr2)
print("Division:\n", arr1 / arr2)
print("Modulus:\n", arr1 % arr2)

# Arithmatic operations on arrays using functions
arr3 = np.random.randint(20,30,(3,4))
arr4 = np.random.randint(30,40,(3,4))

print("Sum:\n", np.add(arr3,arr4))
print("Subtraction:\n", np.subtract(arr3,arr4))
print("Multiplication:\n", np.multiply(arr3,arr4))
print("Division:\n", np.divide(arr3,arr4))
print("Modulus:\n", np.mod(arr3,arr4))

# 5, Array Manipulation

# Transpose of array using function
array1 = np.random.randint(0,10,(4,5))
print("Array-1:\n", array1)

trans_array1 = np.transpose(array1)
print("Transposed Array-1 with function:\n", trans_array1)

# Transpose of array using attribute 'T'
array2 = np.random.randint(0,20,(4,5))
print("Array-2:\n", array2)

trans_array2 = array2.T
print("Transposed Array-2 with attribute 'T':\n", trans_array2)

# Reshaping array
norm_array = np.random.randint(0,20,(4,5))
print("Normal Array:\n", norm_array)

resh_array = norm_array.reshape(5,4)
print("Reshaped Array:\n", resh_array)



1D Array:
 [ 3 53 34  3  3]
Multi-dimensional Array:
 [[ 2 32  2  3]
 [ 3  4  3  2]
 [ 3 42  4  2]]
Representation in floating data type:
 [[ 3.  3.  5.  3.]
 [ 2.  5.  2.  4.]
 [ 3. 53.  4. 34.]]
Placeholder - 0 Array:
 [[0. 0. 0.]
 [0. 0. 0.]]
Placeholder - 1 Array:
 [[1. 1. 1.]
 [1. 1. 1.]]
Particular value array:
 [[5 5 5]
 [5 5 5]
 [5 5 5]]
Identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Random value array:
 [[0.67680645 0.08753838 0.5067656  0.76886875 0.19996405]
 [0.94940953 0.96814234 0.57033894 0.1312344  0.6809703 ]
 [0.16075158 0.38706461 0.41850256 0.00856146 0.97686313]
 [0.43298475 0.93119057 0.6688203  0.07682303 0.60355168]]
Random value array with specific range:
 [[6 5 2 6 1]
 [6 0 7 4 4]
 [1 6 9 7 0]
 [4 4 9 8 4]]
Evenly spaced array with required number of values:
 [ 0.  4.  8. 12. 16. 20.]
Evenly spaced array with stepsize:
 [ 0  6 12 18]
Coverted list to array:
 [ 1  4 24  4  4]
Shape of arr:
 (4, 4)
Dimension of arr:
 2
Size of the arr:
 16
Data type of a